### PR TITLE
ENH: Allow not printing coverage report

### LINKED ISSUE #829: ENH: Allow not printing coverage report
I use `nose` in a number of projects to test code and determine coverage using the built-in `cover` plugin, and it works great. We use the generated `.coverage` file to submit to Coveralls (or generate a subsequent HTML report). However, we do not use the coverage-generated report that prints to the terminal. Since some of the packages have many submodules, this can mean hundreds of extra lines printed during testing that a user must scroll back through to see the source of an error.

I would like to submit a PR to disable printing of the report. I'm pretty sure I would just need to disable this line:

https://github.com/nose-devs/nose/blob/master/nose/plugins/cover.py#L172

I would thus add a command-line option, perhaps `--cover-no-printing`. Thoughts?

### PR DESCRIPTION
**Pull request by Eric89GXL**
Code changes proposed to address #829.

Closes #829.

### CODE REVIEW

**Comment by Trii** [comment]
What is the status of this PR? I would like this option as well.

**Comment by Eric89GXL** [comment]
Ready to go from my end as of ~6 months ago.

**Comment by cp2587** [comment]
Can this be merge ? Would be a good addition

**Comment by Eric89GXL** [comment]
It can no longer be automatically merged (merge conflict). I'm happy to rebase, though, if the maintainers want this addition.

**Comment by Eric89GXL** [comment]
@jszakmeister any comment on this one? I'm happy to rebase if necessary. Would be nice to have this option eventually.

**Comment by Eric89GXL** [comment]
Rebase complete and Travis is happy.

**Comment by jszakmeister** [comment]
A couple of comments.  I've seen others do this, but I'm not real fond of the "FIX", "STY", and "ENH" prefixes on commit messages.  Also, there were a number of unrelated stylistic fixes in there too.  I realize your editor probably helped you "fix" them, but it detracts from the actual changes that you make.  I mention it because a number of projects would outright reject patches that did that, and I think it's best to error on the side of caution and refrain from it when contributing to other projects.

That said, thank you.  I'll merge this now.

FWIW, I'm [stepping down as maintainer](https://groups.google.com/forum/#!topic/nose-dev/rkofU1WdNNc), so Nose will be unmaintained after I cut the next patch release.

**Comment by Eric89GXL** [comment]
Thanks for the comments, (re-)review, merge, and maintenance effort (even though it's coming to an end soon).

FWIW I do the prefixes because to my eye they have become a de facto standard in the scientific Python ecosystem (e.g., numpy, scipy, scikit-learn), but perhaps they're less common elsewhere in Python.

**Comment by jszakmeister** [comment]
> Thanks for the comments, (re-)review, merge, and maintenance effort (even though it's coming to an end soon).

Thank you.

> FWIW I do the prefixes because to my eye they have become a de facto standard in the scientific Python ecosystem (e.g., numpy, scipy, scikit-learn), but perhaps they're less common elsewhere in Python.

As someone who has contributed to a number of open source projects for the past 15+ years, it's a good idea to see what the project does and follow their standards, instead of having them accept your own.  It's makes the processes smoother, and it's one less thing that a maintainer has to comment on and tell you to fix. :-)

Thanks again. :-)

**Pull request merged**
