### PR TITLE
Adds an option to specify the location of the coverage config file.

### PR DESCRIPTION
**Pull request by brian-reinhart**
Adds an option to specify the location of the coverage config file.

### CODE REVIEW

**Comment by jszakmeister** [comment]
What's the motivation here?  Why do you not have the coverage config file in the same directory that you're running nose?  Also, not much gets merged these days without tests.

**Comment by brian-reinhart** [comment]
Thanks for taking the time to look at this pull request, John.

> What's the motivation here? Why do you not have the coverage config file in the same directory that you're running nose?

I dislike the inconsistency of how different Python projects handle configuration files. Some projects by default use a visible config file, some use a hidden dotfile, others use setup.cfg, etc. In this case, coverage allows me to move the config file but nose doesn't currently pass that configuration forward.

> Also, not much gets merged these days without tests.

I can sympathize. I looked into adding testing for this particular option but it didn't seem like there was significant testing for coverage configuration options to begin with. You can expect the next commit to have additional testing.

**Comment by jszakmeister** [comment]
> I dislike the inconsistency of how different Python projects handle configuration files. Some projects by default use a visible config file, some use a hidden dotfile, others use setup.cfg, etc. In this case, coverage allows me to move the config file but nose doesn't currently pass that configuration forward.

I see.  You want to do it a particular way, and we stand in the way.

> I can sympathize. I looked into adding testing for this particular option but it didn't seem like there was significant testing for coverage configuration options to begin with. You can expect the next commit to have additional testing.

That happens, yes.  Nose has been around a while, and even though there a lots of tests, it still lacks in some areas.  The project's standards have evolved over time, so some portions are lacking.  Thank you for improving the situation.

**Comment by brian-reinhart** [comment]
> I see. You want to do it a particular way, and we stand in the way.

Thank you for understanding.

**Comment by brian-reinhart** [comment]
Ping.

I just wanted to get an update on the status of this and if there is anything left for me to do.

**Comment by jszakmeister** [comment]
Can you fix up the history to squash the relevant fix commits into the original ones?  Sorry, but I'm a bit picky about that stuff, especially since I spend so much time tracking down bugs.

**Comment by jszakmeister** [comment]
Merged an amended version of this in 0f592c4b022bf3226bd970ccc8c09fea899b2960.

**Pull request closed without merging**
