### PR TITLE
minor spelling fix

### PR DESCRIPTION
**Pull request by Wilfred**

### CODE REVIEW

**Comment by jayvdb** [comment]
Nearly three years to merge some spelling mistakes in documentation?? wow.

**Comment by jwilk** [comment]
This typo was fixed in d9120b5de3c6 and d22b74668fc7.

**Comment by jayvdb** [comment]
Yup, @Wilfred, looks like this can be closed.

**Comment by Wilfred** [comment]
Thanks folks :)

**Pull request closed without merging**
