### PR TITLE
Add Python 3.4 to travis build.

### PR DESCRIPTION
**Pull request by OddBloke**

### CODE REVIEW

**Comment by montefra** [comment]
with PR #927 I'm testing if I manage to solve a deadlock in python 3.4. Do you mind if I cherry-pick your commit to test my changes on travis?

**Comment by OddBloke** [comment]
Feel free, though better would be to convince someone to merge this and then rebase on top of master. :p

**Comment by montefra** [comment]
I know.

I can pick your commit and remove it when travis runs without errors.

**Comment by jszakmeister** [comment]
Thanks.

**Pull request merged**
